# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7aeebcc9c6ae85770e608bfe48c5d2d550b134056a6e11a956062b9c20379bd8fcdcacbc2dc0592d04f0971aca29a5148dd5601a2c27d8992cef2a10ceb191e3

test:
  secret_key_base: a6b03dcb47dd69b53c41c0f3c0cbf138dc1ff3cd8cfb6cb8ffbe0582ad51f490adcecd8e37d3eec8c4aec91191653cd0dfd284ae3220c6697612a35331eb3179

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
